### ISSUE TITLE
fix: python 3.8 compiled with libffi6 does not fit ubuntu 20.04

### ISSUE THREAD

**Issue by tristanrobert** [Scalingo/python-buildpack#56]
scalingo-20 is ubuntu 20.04 (focal) and libffi is 7.
python-buildpack installs v3.8 compiled with libffi6.

requirements with ofxparse 0.21 (latest) has error:

```shell
Collecting ofxparse==0.21
         Downloading ofxparse-0.21.tar.gz (53 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'error'
         ERROR: Command errored out with exit status 1:
          command: /app/.scalingo/python/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zu_8qni9/ofxparse_3a3f4dc08deb4d8793c9d5abf8d16581/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zu_8qni9/ofxparse_3a3f4dc08deb4d8793c9d5abf8d16581/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xt67u2tf
              cwd: /tmp/pip-install-zu_8qni9/ofxparse_3a3f4dc08deb4d8793c9d5abf8d16581/
         Complete output (11 lines):
         Traceback (most recent call last):
           File "<string>", line 1, in <module>
           File "/app/.scalingo/python/lib/python3.8/site-packages/setuptools/__init__.py", line 18, in <module>
             from setuptools.dist import Distribution
           File "/app/.scalingo/python/lib/python3.8/site-packages/setuptools/dist.py", line 38, in <module>
             from setuptools import windows_support
           File "/app/.scalingo/python/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
             import ctypes
           File "/app/.scalingo/python/lib/python3.8/ctypes/__init__.py", line 7, in <module>
             from _ctypes import Union, Structure, Array
         ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```
Is it possible to install python 3.8 compiled with libffi7 in ubuntu focal?

**Comment by matthieu526-scalingo** [comment]
Closing this error as we don't support scalingo-20.
